#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_21806064393.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="webaccgame")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTuong(Tuong instance);
    partial void UpdateTuong(Tuong instance);
    partial void DeleteTuong(Tuong instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    partial void Insertthecao(thecao instance);
    partial void Updatethecao(thecao instance);
    partial void Deletethecao(thecao instance);
    partial void InsertCart(Cart instance);
    partial void UpdateCart(Cart instance);
    partial void DeleteCart(Cart instance);
    partial void Insertacc(acc instance);
    partial void Updateacc(acc instance);
    partial void Deleteacc(acc instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void Insertmbbank(mbbank instance);
    partial void Updatembbank(mbbank instance);
    partial void Deletembbank(mbbank instance);
    partial void InsertBalanceHistory(BalanceHistory instance);
    partial void UpdateBalanceHistory(BalanceHistory instance);
    partial void DeleteBalanceHistory(BalanceHistory instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public DataClasses1DataContext() :
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["webaccgameConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }
        public System.Data.Linq.Table<Tuong> Tuongs
		{
			get
			{
				return this.GetTable<Tuong>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		public System.Data.Linq.Table<thecao> thecaos
		{
			get
			{
				return this.GetTable<thecao>();
			}
		}
		
		public System.Data.Linq.Table<Cart> Carts
		{
			get
			{
				return this.GetTable<Cart>();
			}
		}
		
		public System.Data.Linq.Table<acc> accs
		{
			get
			{
				return this.GetTable<acc>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<mbbank> mbbanks
		{
			get
			{
				return this.GetTable<mbbank>();
			}
		}
		
		public System.Data.Linq.Table<BalanceHistory> BalanceHistories
		{
			get
			{
				return this.GetTable<BalanceHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tuong")]
	public partial class Tuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tuong;
		
		private string _ma_tuong;
		
		private string _imageURLtuong;
		
		private string _name_tuong;
		
		private System.Nullable<int> _id_acc;
		
		private EntityRef<acc> _acc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tuongChanging(int value);
    partial void Onid_tuongChanged();
    partial void Onma_tuongChanging(string value);
    partial void Onma_tuongChanged();
    partial void OnimageURLtuongChanging(string value);
    partial void OnimageURLtuongChanged();
    partial void Onname_tuongChanging(string value);
    partial void Onname_tuongChanged();
    partial void Onid_accChanging(System.Nullable<int> value);
    partial void Onid_accChanged();
    #endregion
		
		public Tuong()
		{
			this._acc = default(EntityRef<acc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tuong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tuong
		{
			get
			{
				return this._id_tuong;
			}
			set
			{
				if ((this._id_tuong != value))
				{
					this.Onid_tuongChanging(value);
					this.SendPropertyChanging();
					this._id_tuong = value;
					this.SendPropertyChanged("id_tuong");
					this.Onid_tuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_tuong", DbType="NVarChar(50)")]
		public string ma_tuong
		{
			get
			{
				return this._ma_tuong;
			}
			set
			{
				if ((this._ma_tuong != value))
				{
					this.Onma_tuongChanging(value);
					this.SendPropertyChanging();
					this._ma_tuong = value;
					this.SendPropertyChanged("ma_tuong");
					this.Onma_tuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURLtuong", DbType="NVarChar(50)")]
		public string imageURLtuong
		{
			get
			{
				return this._imageURLtuong;
			}
			set
			{
				if ((this._imageURLtuong != value))
				{
					this.OnimageURLtuongChanging(value);
					this.SendPropertyChanging();
					this._imageURLtuong = value;
					this.SendPropertyChanged("imageURLtuong");
					this.OnimageURLtuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_tuong", DbType="NVarChar(50)")]
		public string name_tuong
		{
			get
			{
				return this._name_tuong;
			}
			set
			{
				if ((this._name_tuong != value))
				{
					this.Onname_tuongChanging(value);
					this.SendPropertyChanging();
					this._name_tuong = value;
					this.SendPropertyChanged("name_tuong");
					this.Onname_tuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_acc", DbType="Int")]
		public System.Nullable<int> id_acc
		{
			get
			{
				return this._id_acc;
			}
			set
			{
				if ((this._id_acc != value))
				{
					if (this._acc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_accChanging(value);
					this.SendPropertyChanging();
					this._id_acc = value;
					this.SendPropertyChanged("id_acc");
					this.Onid_accChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acc_Tuong", Storage="_acc", ThisKey="id_acc", OtherKey="id_acc", IsForeignKey=true)]
		public acc acc
		{
			get
			{
				return this._acc.Entity;
			}
			set
			{
				acc previousValue = this._acc.Entity;
				if (((previousValue != value) 
							|| (this._acc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._acc.Entity = null;
						previousValue.Tuongs.Remove(this);
					}
					this._acc.Entity = value;
					if ((value != null))
					{
						value.Tuongs.Add(this);
						this._id_acc = value.id_acc;
					}
					else
					{
						this._id_acc = default(Nullable<int>);
					}
					this.SendPropertyChanged("acc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_giohang;
		
		private System.Nullable<int> _idnick;
		
		private System.Nullable<decimal> _gianick;
		
		private string _image;
		
		private System.Nullable<decimal> _Total;
		
		private string _userN;
		
		private string _acc_count;
		
		private string _pass_word;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_giohangChanging(int value);
    partial void Onid_giohangChanged();
    partial void OnidnickChanging(System.Nullable<int> value);
    partial void OnidnickChanged();
    partial void OngianickChanging(System.Nullable<decimal> value);
    partial void OngianickChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnuserNChanging(string value);
    partial void OnuserNChanged();
    partial void Onacc_countChanging(string value);
    partial void Onacc_countChanged();
    partial void Onpass_wordChanging(string value);
    partial void Onpass_wordChanged();
    #endregion
		
		public GioHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_giohang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_giohang
		{
			get
			{
				return this._id_giohang;
			}
			set
			{
				if ((this._id_giohang != value))
				{
					this.Onid_giohangChanging(value);
					this.SendPropertyChanging();
					this._id_giohang = value;
					this.SendPropertyChanged("id_giohang");
					this.Onid_giohangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idnick", DbType="Int")]
		public System.Nullable<int> idnick
		{
			get
			{
				return this._idnick;
			}
			set
			{
				if ((this._idnick != value))
				{
					this.OnidnickChanging(value);
					this.SendPropertyChanging();
					this._idnick = value;
					this.SendPropertyChanged("idnick");
					this.OnidnickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gianick", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> gianick
		{
			get
			{
				return this._gianick;
			}
			set
			{
				if ((this._gianick != value))
				{
					this.OngianickChanging(value);
					this.SendPropertyChanging();
					this._gianick = value;
					this.SendPropertyChanged("gianick");
					this.OngianickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(255)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userN", DbType="NVarChar(255)")]
		public string userN
		{
			get
			{
				return this._userN;
			}
			set
			{
				if ((this._userN != value))
				{
					this.OnuserNChanging(value);
					this.SendPropertyChanging();
					this._userN = value;
					this.SendPropertyChanged("userN");
					this.OnuserNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acc_count", DbType="NVarChar(255)")]
		public string acc_count
		{
			get
			{
				return this._acc_count;
			}
			set
			{
				if ((this._acc_count != value))
				{
					this.Onacc_countChanging(value);
					this.SendPropertyChanging();
					this._acc_count = value;
					this.SendPropertyChanged("acc_count");
					this.Onacc_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass_word", DbType="NVarChar(255)")]
		public string pass_word
		{
			get
			{
				return this._pass_word;
			}
			set
			{
				if ((this._pass_word != value))
				{
					this.Onpass_wordChanging(value);
					this.SendPropertyChanging();
					this._pass_word = value;
					this.SendPropertyChanged("pass_word");
					this.Onpass_wordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thecao")]
	public partial class thecao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idthecao;
		
		private string _type;
		
		private int _menhgia;
		
		private string _seri;
		
		private string _pin;
		
		private string _APIKey;
		
		private string _callback;
		
		private string _content;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _tenuser;
		
		private string _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidthecaoChanging(int value);
    partial void OnidthecaoChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnmenhgiaChanging(int value);
    partial void OnmenhgiaChanged();
    partial void OnseriChanging(string value);
    partial void OnseriChanged();
    partial void OnpinChanging(string value);
    partial void OnpinChanged();
    partial void OnAPIKeyChanging(string value);
    partial void OnAPIKeyChanged();
    partial void OncallbackChanging(string value);
    partial void OncallbackChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OntenuserChanging(string value);
    partial void OntenuserChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public thecao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idthecao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idthecao
		{
			get
			{
				return this._idthecao;
			}
			set
			{
				if ((this._idthecao != value))
				{
					this.OnidthecaoChanging(value);
					this.SendPropertyChanging();
					this._idthecao = value;
					this.SendPropertyChanged("idthecao");
					this.OnidthecaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_menhgia", DbType="Int NOT NULL")]
		public int menhgia
		{
			get
			{
				return this._menhgia;
			}
			set
			{
				if ((this._menhgia != value))
				{
					this.OnmenhgiaChanging(value);
					this.SendPropertyChanging();
					this._menhgia = value;
					this.SendPropertyChanged("menhgia");
					this.OnmenhgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seri", DbType="NVarChar(MAX)")]
		public string seri
		{
			get
			{
				return this._seri;
			}
			set
			{
				if ((this._seri != value))
				{
					this.OnseriChanging(value);
					this.SendPropertyChanging();
					this._seri = value;
					this.SendPropertyChanged("seri");
					this.OnseriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", DbType="NVarChar(MAX)")]
		public string pin
		{
			get
			{
				return this._pin;
			}
			set
			{
				if ((this._pin != value))
				{
					this.OnpinChanging(value);
					this.SendPropertyChanging();
					this._pin = value;
					this.SendPropertyChanged("pin");
					this.OnpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APIKey", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string APIKey
		{
			get
			{
				return this._APIKey;
			}
			set
			{
				if ((this._APIKey != value))
				{
					this.OnAPIKeyChanging(value);
					this.SendPropertyChanging();
					this._APIKey = value;
					this.SendPropertyChanged("APIKey");
					this.OnAPIKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_callback", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string callback
		{
			get
			{
				return this._callback;
			}
			set
			{
				if ((this._callback != value))
				{
					this.OncallbackChanging(value);
					this.SendPropertyChanging();
					this._callback = value;
					this.SendPropertyChanged("callback");
					this.OncallbackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenuser", DbType="NVarChar(255)")]
		public string tenuser
		{
			get
			{
				return this._tenuser;
			}
			set
			{
				if ((this._tenuser != value))
				{
					this.OntenuserChanging(value);
					this.SendPropertyChanging();
					this._tenuser = value;
					this.SendPropertyChanged("tenuser");
					this.OntenuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NVarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
	public partial class Cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cartid;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _idacc;
		
		private System.Nullable<decimal> _priceacc;
		
		private System.Nullable<decimal> _sotien;
		
		private string _userName;
		
		private string _taikhoan;
		
		private string _pass;
		
		private EntityRef<acc> _acc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncartidChanging(int value);
    partial void OncartidChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnidaccChanging(System.Nullable<int> value);
    partial void OnidaccChanged();
    partial void OnpriceaccChanging(System.Nullable<decimal> value);
    partial void OnpriceaccChanged();
    partial void OnsotienChanging(System.Nullable<decimal> value);
    partial void OnsotienChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnpassChanging(string value);
    partial void OnpassChanged();
    #endregion
		
		public Cart()
		{
			this._acc = default(EntityRef<acc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cartid
		{
			get
			{
				return this._cartid;
			}
			set
			{
				if ((this._cartid != value))
				{
					this.OncartidChanging(value);
					this.SendPropertyChanging();
					this._cartid = value;
					this.SendPropertyChanged("cartid");
					this.OncartidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idacc", DbType="Int")]
		public System.Nullable<int> idacc
		{
			get
			{
				return this._idacc;
			}
			set
			{
				if ((this._idacc != value))
				{
					if (this._acc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidaccChanging(value);
					this.SendPropertyChanging();
					this._idacc = value;
					this.SendPropertyChanged("idacc");
					this.OnidaccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceacc", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> priceacc
		{
			get
			{
				return this._priceacc;
			}
			set
			{
				if ((this._priceacc != value))
				{
					this.OnpriceaccChanging(value);
					this.SendPropertyChanging();
					this._priceacc = value;
					this.SendPropertyChanged("priceacc");
					this.OnpriceaccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> sotien
		{
			get
			{
				return this._sotien;
			}
			set
			{
				if ((this._sotien != value))
				{
					this.OnsotienChanging(value);
					this.SendPropertyChanging();
					this._sotien = value;
					this.SendPropertyChanged("sotien");
					this.OnsotienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="NVarChar(50)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pass", DbType="NVarChar(50)")]
		public string pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				if ((this._pass != value))
				{
					this.OnpassChanging(value);
					this.SendPropertyChanging();
					this._pass = value;
					this.SendPropertyChanged("pass");
					this.OnpassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acc_Cart", Storage="_acc", ThisKey="idacc", OtherKey="id_acc", IsForeignKey=true)]
		public acc acc
		{
			get
			{
				return this._acc.Entity;
			}
			set
			{
				acc previousValue = this._acc.Entity;
				if (((previousValue != value) 
							|| (this._acc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._acc.Entity = null;
						previousValue.Carts.Remove(this);
					}
					this._acc.Entity = value;
					if ((value != null))
					{
						value.Carts.Add(this);
						this._idacc = value.id_acc;
					}
					else
					{
						this._idacc = default(Nullable<int>);
					}
					this.SendPropertyChanged("acc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.acc")]
	public partial class acc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_acc;
		
		private string _account;
		
		private string _password;
		
		private System.Nullable<int> _so_mau_mat;
		
		private System.Nullable<int> _so_tuong;
		
		private System.Nullable<int> _so_skin;
		
		private System.Nullable<decimal> _gia;
		
		private string _imageURL;
		
		private string _status;
		
		private string _theloai;
		
		private System.Nullable<int> _khuyenmai;
		
		private System.Nullable<decimal> _giasaukhuyenmai;
		
		private string _rank;
		
		private string _matuong;
		
		private EntitySet<Tuong> _Tuongs;
		
		private EntitySet<Cart> _Carts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_accChanging(int value);
    partial void Onid_accChanged();
    partial void OnaccountChanging(string value);
    partial void OnaccountChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onso_mau_matChanging(System.Nullable<int> value);
    partial void Onso_mau_matChanged();
    partial void Onso_tuongChanging(System.Nullable<int> value);
    partial void Onso_tuongChanged();
    partial void Onso_skinChanging(System.Nullable<int> value);
    partial void Onso_skinChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void OnimageURLChanging(string value);
    partial void OnimageURLChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OntheloaiChanging(string value);
    partial void OntheloaiChanged();
    partial void OnkhuyenmaiChanging(System.Nullable<int> value);
    partial void OnkhuyenmaiChanged();
    partial void OngiasaukhuyenmaiChanging(System.Nullable<decimal> value);
    partial void OngiasaukhuyenmaiChanged();
    partial void OnrankChanging(string value);
    partial void OnrankChanged();
    partial void OnmatuongChanging(string value);
    partial void OnmatuongChanged();
    #endregion
		
		public acc()
		{
			this._Tuongs = new EntitySet<Tuong>(new Action<Tuong>(this.attach_Tuongs), new Action<Tuong>(this.detach_Tuongs));
			this._Carts = new EntitySet<Cart>(new Action<Cart>(this.attach_Carts), new Action<Cart>(this.detach_Carts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_acc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_acc
		{
			get
			{
				return this._id_acc;
			}
			set
			{
				if ((this._id_acc != value))
				{
					this.Onid_accChanging(value);
					this.SendPropertyChanging();
					this._id_acc = value;
					this.SendPropertyChanged("id_acc");
					this.Onid_accChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string account
		{
			get
			{
				return this._account;
			}
			set
			{
				if ((this._account != value))
				{
					this.OnaccountChanging(value);
					this.SendPropertyChanging();
					this._account = value;
					this.SendPropertyChanged("account");
					this.OnaccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_mau_mat", DbType="Int")]
		public System.Nullable<int> so_mau_mat
		{
			get
			{
				return this._so_mau_mat;
			}
			set
			{
				if ((this._so_mau_mat != value))
				{
					this.Onso_mau_matChanging(value);
					this.SendPropertyChanging();
					this._so_mau_mat = value;
					this.SendPropertyChanged("so_mau_mat");
					this.Onso_mau_matChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_tuong", DbType="Int")]
		public System.Nullable<int> so_tuong
		{
			get
			{
				return this._so_tuong;
			}
			set
			{
				if ((this._so_tuong != value))
				{
					this.Onso_tuongChanging(value);
					this.SendPropertyChanging();
					this._so_tuong = value;
					this.SendPropertyChanged("so_tuong");
					this.Onso_tuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_skin", DbType="Int")]
		public System.Nullable<int> so_skin
		{
			get
			{
				return this._so_skin;
			}
			set
			{
				if ((this._so_skin != value))
				{
					this.Onso_skinChanging(value);
					this.SendPropertyChanging();
					this._so_skin = value;
					this.SendPropertyChanged("so_skin");
					this.Onso_skinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageURL", DbType="VarChar(255)")]
		public string imageURL
		{
			get
			{
				return this._imageURL;
			}
			set
			{
				if ((this._imageURL != value))
				{
					this.OnimageURLChanging(value);
					this.SendPropertyChanging();
					this._imageURL = value;
					this.SendPropertyChanged("imageURL");
					this.OnimageURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theloai", DbType="VarChar(50)")]
		public string theloai
		{
			get
			{
				return this._theloai;
			}
			set
			{
				if ((this._theloai != value))
				{
					this.OntheloaiChanging(value);
					this.SendPropertyChanging();
					this._theloai = value;
					this.SendPropertyChanged("theloai");
					this.OntheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyenmai", DbType="Int")]
		public System.Nullable<int> khuyenmai
		{
			get
			{
				return this._khuyenmai;
			}
			set
			{
				if ((this._khuyenmai != value))
				{
					this.OnkhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._khuyenmai = value;
					this.SendPropertyChanged("khuyenmai");
					this.OnkhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giasaukhuyenmai", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> giasaukhuyenmai
		{
			get
			{
				return this._giasaukhuyenmai;
			}
			set
			{
				if ((this._giasaukhuyenmai != value))
				{
					this.OngiasaukhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._giasaukhuyenmai = value;
					this.SendPropertyChanged("giasaukhuyenmai");
					this.OngiasaukhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rank", DbType="NVarChar(50)")]
		public string rank
		{
			get
			{
				return this._rank;
			}
			set
			{
				if ((this._rank != value))
				{
					this.OnrankChanging(value);
					this.SendPropertyChanging();
					this._rank = value;
					this.SendPropertyChanged("rank");
					this.OnrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matuong", DbType="NVarChar(MAX)")]
		public string matuong
		{
			get
			{
				return this._matuong;
			}
			set
			{
				if ((this._matuong != value))
				{
					this.OnmatuongChanging(value);
					this.SendPropertyChanging();
					this._matuong = value;
					this.SendPropertyChanged("matuong");
					this.OnmatuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acc_Tuong", Storage="_Tuongs", ThisKey="id_acc", OtherKey="id_acc")]
		public EntitySet<Tuong> Tuongs
		{
			get
			{
				return this._Tuongs;
			}
			set
			{
				this._Tuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="acc_Cart", Storage="_Carts", ThisKey="id_acc", OtherKey="idacc")]
		public EntitySet<Cart> Carts
		{
			get
			{
				return this._Carts;
			}
			set
			{
				this._Carts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tuongs(Tuong entity)
		{
			this.SendPropertyChanging();
			entity.acc = this;
		}
		
		private void detach_Tuongs(Tuong entity)
		{
			this.SendPropertyChanging();
			entity.acc = null;
		}
		
		private void attach_Carts(Cart entity)
		{
			this.SendPropertyChanging();
			entity.acc = this;
		}
		
		private void detach_Carts(Cart entity)
		{
			this.SendPropertyChanging();
			entity.acc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _username;
		
		private string _password;
		
		private System.Nullable<int> _roles;
		
		private System.Nullable<decimal> _price;
		
		private string _gmail;
		
		private System.Nullable<int> _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnrolesChanging(System.Nullable<int> value);
    partial void OnrolesChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OngmailChanging(string value);
    partial void OngmailChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roles", DbType="Int")]
		public System.Nullable<int> roles
		{
			get
			{
				return this._roles;
			}
			set
			{
				if ((this._roles != value))
				{
					this.OnrolesChanging(value);
					this.SendPropertyChanging();
					this._roles = value;
					this.SendPropertyChanged("roles");
					this.OnrolesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmail", DbType="VarChar(50)")]
		public string gmail
		{
			get
			{
				return this._gmail;
			}
			set
			{
				if ((this._gmail != value))
				{
					this.OngmailChanging(value);
					this.SendPropertyChanging();
					this._gmail = value;
					this.SendPropertyChanged("gmail");
					this.OngmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}

        public string ConfirmPassword { get; set; }

        public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mbbank")]
	public partial class mbbank : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_mbbank;
		
		private string _magd;
		
		private System.Nullable<decimal> _sodu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaytao;
		
		private string _trangthai;
		
		private string _taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_mbbankChanging(int value);
    partial void Onid_mbbankChanged();
    partial void OnmagdChanging(string value);
    partial void OnmagdChanged();
    partial void OnsoduChanging(System.Nullable<decimal> value);
    partial void OnsoduChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaytaoChanging(System.Nullable<System.DateTime> value);
    partial void OnngaytaoChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    #endregion
		
		public mbbank()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_mbbank", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_mbbank
		{
			get
			{
				return this._id_mbbank;
			}
			set
			{
				if ((this._id_mbbank != value))
				{
					this.Onid_mbbankChanging(value);
					this.SendPropertyChanging();
					this._id_mbbank = value;
					this.SendPropertyChanged("id_mbbank");
					this.Onid_mbbankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magd", DbType="NVarChar(255)")]
		public string magd
		{
			get
			{
				return this._magd;
			}
			set
			{
				if ((this._magd != value))
				{
					this.OnmagdChanging(value);
					this.SendPropertyChanging();
					this._magd = value;
					this.SendPropertyChanged("magd");
					this.OnmagdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> sodu
		{
			get
			{
				return this._sodu;
			}
			set
			{
				if ((this._sodu != value))
				{
					this.OnsoduChanging(value);
					this.SendPropertyChanging();
					this._sodu = value;
					this.SendPropertyChanged("sodu");
					this.OnsoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(255)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaytao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaytao
		{
			get
			{
				return this._ngaytao;
			}
			set
			{
				if ((this._ngaytao != value))
				{
					this.OnngaytaoChanging(value);
					this.SendPropertyChanging();
					this._ngaytao = value;
					this.SendPropertyChanged("ngaytao");
					this.OnngaytaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="NVarChar(255)")]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="NVarChar(255)")]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BalanceHistory")]
	public partial class BalanceHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_balance;
		
		private string _username;
		
		private decimal _amount_before;
		
		private decimal _amount_after;
		
		private decimal _current_balance;
		
		private System.DateTime _transaction_date;
		
		private string _content;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_balanceChanging(int value);
    partial void Onid_balanceChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onamount_beforeChanging(decimal value);
    partial void Onamount_beforeChanged();
    partial void Onamount_afterChanging(decimal value);
    partial void Onamount_afterChanged();
    partial void Oncurrent_balanceChanging(decimal value);
    partial void Oncurrent_balanceChanged();
    partial void Ontransaction_dateChanging(System.DateTime value);
    partial void Ontransaction_dateChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    #endregion
		
		public BalanceHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_balance", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_balance
		{
			get
			{
				return this._id_balance;
			}
			set
			{
				if ((this._id_balance != value))
				{
					this.Onid_balanceChanging(value);
					this.SendPropertyChanging();
					this._id_balance = value;
					this.SendPropertyChanged("id_balance");
					this.Onid_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_before", DbType="Decimal(18,2) NOT NULL")]
		public decimal amount_before
		{
			get
			{
				return this._amount_before;
			}
			set
			{
				if ((this._amount_before != value))
				{
					this.Onamount_beforeChanging(value);
					this.SendPropertyChanging();
					this._amount_before = value;
					this.SendPropertyChanged("amount_before");
					this.Onamount_beforeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_after", DbType="Decimal(18,2) NOT NULL")]
		public decimal amount_after
		{
			get
			{
				return this._amount_after;
			}
			set
			{
				if ((this._amount_after != value))
				{
					this.Onamount_afterChanging(value);
					this.SendPropertyChanging();
					this._amount_after = value;
					this.SendPropertyChanged("amount_after");
					this.Onamount_afterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_balance", DbType="Decimal(18,2) NOT NULL")]
		public decimal current_balance
		{
			get
			{
				return this._current_balance;
			}
			set
			{
				if ((this._current_balance != value))
				{
					this.Oncurrent_balanceChanging(value);
					this.SendPropertyChanging();
					this._current_balance = value;
					this.SendPropertyChanged("current_balance");
					this.Oncurrent_balanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transaction_date", DbType="DateTime NOT NULL")]
		public System.DateTime transaction_date
		{
			get
			{
				return this._transaction_date;
			}
			set
			{
				if ((this._transaction_date != value))
				{
					this.Ontransaction_dateChanging(value);
					this.SendPropertyChanging();
					this._transaction_date = value;
					this.SendPropertyChanged("transaction_date");
					this.Ontransaction_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
